//include("old-server-localhost")
include("plugin-github-token")
include("github")
include("client")
include("network")
include("lib")
include("lib-mvi")
include("lib-redux")
include("ci-panel-mvi")
include("local-server")//todo rename to localhost-server
include("ci-panel-view")
